version: "3"

services:
  web:
    container_name: frapi
    build:
      context: .
      dockerfile: ./frapi-django/Dockerfile
      args:
        - http_proxy
        - https_proxy
    command: bash -c "python ./frapi-django/frapi/manage.py makemigrations
             && python ./frapi-django/frapi/manage.py migrate
             && python ./frapi-django/frapi/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - db_network
  db:
    restart: always
    container_name: frapi_mondodb
    build:
      context: .
      dockerfile: ./frapi-db/Dockerfile
      args:
        - http_proxy
        - https_proxy
    ports:
      - 27017:27017
    networks:
      - db_network

networks:
  db_network: