# Generated by Django 2.2 on 2019-04-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='John', max_length=100)),
                ('prenom', models.CharField(default='Doe', max_length=100)),
                ('situation', models.CharField(blank=True, default='Situation inconnue', max_length=1000)),
                ('date_de_naissance', models.DateTimeField()),
                ('age', models.IntegerField(default=60)),
                ('departement', models.CharField(default='departement inconnu', max_length=100)),
                ('commune', models.CharField(default='Commune inconnu', max_length=100)),
                ('civilite', models.CharField(default='Mme', max_length=3)),
            ],
            options={
                'ordering': ('id', 'age'),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='John', max_length=100)),
                ('code', models.CharField(default='75000', max_length=100)),
            ],
            options={
                'ordering': ('id', 'code'),
            },
        ),
    ]
